FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY SocialCareManager.Web/SocialCareManager.Web.csproj SocialCareManager.Web/

RUN dotnet restore SocialCareManager.Web/SocialCareManager.Web.csproj

COPY SocialCareManager.Web/ SocialCareManager.Web/

RUN dotnet publish SocialCareManager.Web/SocialCareManager.Web.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app .

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "SocialCareManager.Web.dll"]